//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APR400_lab2_max_jern
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareTaker
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CareGiverId { get; set; }
    
        public virtual CareGiver CareGiver { get; set; }
    }
}
