//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APR400_lab2_max_jern
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareGivingDBEntities : DbContext
    {
        public CareGivingDBEntities()
            : base("name=CareGivingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CareCenter> CareCenter { get; set; }
        public virtual DbSet<CareGiver> CareGiver { get; set; }
        public virtual DbSet<CareTaker> CareTaker { get; set; }
    }
}
